openapi: 3.0.0
info:
  title: VodafoneZiggo demo
  description: Create and view orders
  version: 1.0.0

paths:
  /orders:
    get:
      summary: Returns a list of orders.
      description: Returns a list of all the orders.
      responses:
        '200':
          description: An array of orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
    post:
      summary: Create new order
      description: Create a new order in the database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productId:
                  type: string
                email:
                  type: string
      responses:
        '201':
          description: Created
          content:
            text/plain:
              schema:
                type: string
                example: "d1f9e6ff-03ac-477e-be4c-b3bfa5161835"
        '404':
          description: The email does not exist in https://reqres.in/api/users
        '400':
          description: The user has already ordered this item
        default:
          description: Unexpected error
components:
  schemas:
    Order:
      type: object
      properties:
        orderId:
          type: string
          example: "d1f9e6ff-03ac-477e-be4c-b3bfa5161835"
        email:
          type: string
          example: "example@example.com"
        productId:
          type: number
          example: 1234
        first_name:
          type: string
          example: "Jan"
        last_name:
          type: string
          example: "Jansen"
      xml:
        name: order
